version: "3.8"
services:
  site:
    image: jekyll-site
    command: >
      jekyll serve
      --incremental
      --force_polling
      --watch
      --livereload
      --drafts
      --host 0.0.0.0
    volumes:
      - .:/srv/jekyll:delegated
  
    ports:
      - "4000:4000"